/*
 * defines for malloc string routines...
 *
 * Copyright 1993 by the Antaire Corporation
 *
 * This file is part of the malloc-debug package.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose and without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies, and that
 * the name of Antaire not be used in advertising or publicity pertaining to
 * distribution of the document or software without specific, written prior
 * permission.
 *
 * The Antaire Corporation makes no representations about the suitability of
 * the software described herein for any purpose.  It is provided "as is"
 * without express or implied warranty.
 *
 * The author may be contacted at gray.watson@antaire.com
 *
 * $Id: arg_check.h,v 1.2 1993/08/30 20:14:03 gray Exp $
 */

#ifndef __ARG_CHECK_H__
#define __ARG_CHECK_H__

#include "malloc_dbg.h"			/* for MALLOC_SIZE */
#include "malloc_loc.h"			/* for IMPORT */

/*<<<<<<<<<<  The below prototypes are auto-generated by fillproto */

/*
 * dummy function for checking bcmp's arguments.
 */
IMPORT	int	_malloc_bcmp(void * b1, void * b2, MALLOC_SIZE len);

/*
 * dummy function for checking bcopy's arguments.
 */
IMPORT	void	_malloc_bcopy(char * from, char * to, MALLOC_SIZE len);

/*
 * dummy function for checking memcmp's arguments.
 */
IMPORT	int	_malloc_memcmp(void * b1, void * b2, MALLOC_SIZE len);

/*
 * dummy function for checking memcpy's arguments.
 */
IMPORT	char	*_malloc_memcpy(char * to, char * from, MALLOC_SIZE len);

/*
 * dummy function for checking memset's arguments.
 */
IMPORT	char	*_malloc_memset(void * buf, char ch, MALLOC_SIZE len);

/*
 * dummy function for checking index's arguments.
 */
IMPORT	char	*_malloc_index(char * str, char ch);

/*
 * dummy function for checking rindex's arguments.
 */
IMPORT	char	*_malloc_rindex(char * str, char ch);

/*
 * dummy function for checking strcat's arguments.
 */
IMPORT	char	*_malloc_strcat(char * to, char * from);

/*
 * dummy function for checking strcmp's arguments.
 */
IMPORT	int	_malloc_strcmp(char * s1, char * s2);

/*
 * dummy function for checking strlen's arguments.
 */
IMPORT	MALLOC_SIZE	_malloc_strlen(char * str);

/*
 * dummy function for checking strtok's arguments.
 */
IMPORT	char	*_malloc_strtok(char * str, char * sep);

/*
 * dummy function for checking bzero's arguments.
 */
IMPORT	void	_malloc_bzero(void * buf, MALLOC_SIZE len);

/*
 * dummy function for checking memccpy's arguments.
 */
IMPORT	char	*_malloc_memccpy(char * s1, char * s2, char ch,
				 MALLOC_SIZE len);

/*
 * dummy function for checking memchr's arguments.
 */
IMPORT	char	*_malloc_memchr(char * s1, char ch, MALLOC_SIZE len);

/*
 * dummy function for checking strchr's arguments.
 */
IMPORT	char	*_malloc_strchr(char * str, char ch);

/*
 * dummy function for checking strrchr's arguments.
 */
IMPORT	char	*_malloc_strrchr(char * str, char ch);

/*
 * dummy function for checking strcpy's arguments.
 */
IMPORT	char	*_malloc_strcpy(char * to, char * from);

/*
 * dummy function for checking strncpy's arguments.
 */
IMPORT	char	*_malloc_strncpy(char * to, char * from, MALLOC_SIZE len);

/*
 * dummy function for checking strcasecmp's arguments.
 */
IMPORT	int	_malloc_strcasecmp(char * s1, char * s2);

/*
 * dummy function for checking strncasecmp's arguments.
 */
IMPORT	int	_malloc_strncasecmp(char * s1, char * s2, MALLOC_SIZE len);

/*
 * dummy function for checking strspn's arguments.
 */
IMPORT	int	_malloc_strspn(char * str, char * list);

/*
 * dummy function for checking strcspn's arguments.
 */
IMPORT	int	_malloc_strcspn(char * str, char * list);

/*
 * dummy function for checking strncat's arguments.
 */
IMPORT	char	*_malloc_strncat(char * to, char * from, MALLOC_SIZE len);

/*
 * dummy function for checking strncmp's arguments.
 */
IMPORT	int	_malloc_strncmp(char * s1, char * s2, MALLOC_SIZE len);

/*
 * dummy function for checking strpbrk's arguments.
 */
IMPORT	char	*_malloc_strpbrk(char * str, char * list);

/*
 * dummy function for checking strstr's arguments.
 */
IMPORT	char	*_malloc_strstr(char * str, char * pat);

/*<<<<<<<<<<   This is end of the auto-generated output from fillproto. */

#endif /* ! __ARG_CHECK_H__ */
